GEOPY-1530
MiraGeoscience/plate-simulation pull request #17
Opened 2024-05-28 21:38 UTC by domfournier

2024-05-30 20:32 UTC, benk-mira requested changes
I'm still not sure I understand all the out_group mechanics in there, but if it works it works!  Some small requests

2024-05-31 15:14 UTC, domfournier commented on plate_simulation/models/plates.py
> -    @property
Yep, I like it.

2024-05-31 15:14 UTC, domfournier commented on plate_simulation/driver.py
> +    def make_surface_from_plate(
Same as above

2024-05-31 18:24 UTC, benk-mira submitted a review, later dismissed

2024-05-31 20:44 UTC, benk-mira approved these changes

2024-05-31 20:45 UTC, merged