DEVOPS-452: Update package with python-conda-template
MiraGeoscience/plate-simulation pull request #28
Opened 2024-07-29 23:56 UTC by SophieCurinier

- Use reusable github workflows
- Use MiraGeoscience/pre-commit-hooks package in `.pre-commit-hooks.yml`
- Update pre-commit-hooks version:
   - `ruff-pre-commit` : v0.5.1
   - `mirrors-mypy`: v1.10.1
   - `Mirageoscience/pre-commit-hooks`: v1.0.0
   - `codespell`: v2.3.0
   - `rstcheck`: v6.2.4

2024-07-31 19:15 UTC, SophieCurinier commented
There is issue in the code due to the dependency octree-creation-app, mira-simpeg and geoapps-utils. This issue need to be check by the Python team.

2024-07-31 21:10 UTC, sebhmg commented on .pre-commit-config.yaml
> +            numpy==1.23.*,
now using 1.26 (also pre-commit CI does not support numpy 1.23)
```suggestion
            numpy==1.26.*,
```

2024-07-31 21:39 UTC, sebhmg commented on .pre-commit-config.yaml
>          ]
```suggestion
            tomli # to read config from pyproject.toml
        ]
       exclude: (conf\.py|tests)
```

2024-07-31 21:40 UTC, sebhmg commented on docs/source/conf.py
> +extensions = []  # type: list[str]
mypy not supposed to run here, thanks to exclusion pattern in pre-commit config
```suggestion
```

2024-07-31 21:40 UTC, sebhmg commented on docs/source/conf.py
> +exclude_patterns = []  # type: list[str]
mypy not supposed to run here, thanks to exclusion pattern in pre-commit config
```suggestion
exclude_patterns = []
```

2024-08-01 13:44 UTC, sebhmg approved these changes

2024-08-01 13:45 UTC, sebhmg requested changes
jobs are now failing but they used to pass on the develop branch

2024-08-02 13:57 UTC, SophieCurinier commented
> jobs are now failing but they used to pass on the develop branch.
> 
> pyproject.toml of geoapps-utils it is pointing at seems invalid: ` ERROR: Could not build wheels for geoapps-utils, which is required to install pyproject.toml-based projects`

I'm not sure how to do it. The issue come from the imported packages. 😞

2024-08-07 18:24 UTC, sebhmg commented
merged through https://github.com/MiraGeoscience/plate-simulation/pull/30

2024-08-07 18:24 UTC, closed without merging